### ISSUE TITLE
redmine install doesn't create a .redmine config file

### ISSUE THREAD

**Issue by micah** [diasjorge/redmine-cli#6]
The readme says to run:
```
redmine install

This will create a .redmine file in your home directory. The file is a yaml file which contains our necessary configuration
```

but when I do that, I am given:
```
You need to create the file .redmine in your home with your username, password and url
```

however, I dont know the format of the file, so I dont know how I should create it!

**Comment by micah** [comment]
It appears that if I touch ~/.redmine, then 'redmine install' will work, it will ask me questions and then say:

```
    conflict  .redmine
Overwrite /home/micah/.redmine? (enter "h" for help) [Ynaqdh] Y
       force  .redmine
```

**Comment by swimfrog** [comment]
Hi micah,

I pushed an update that should fix your problem. Thanks for reporting it. redmine-cli will now print a warning when the config file doesn't exist, but will allow "redmine install" to continue.

Regarding your update:

> It appears that if I touch ~/.redmine, then 'redmine install' will work, it will ask me questions and then say:

The "overwrite" message is there by design, to prevent "redmine install" from accidentally wiping out an existing, tuned configuration file by accident (lots of work went into mine, so I'd be very sad if I accidentally deleted it). Since the install command should now work when no .redmine file exists, this should be less confusing.
