### ISSUE TITLE
How to use version and custom fields?

### ISSUE THREAD

**Issue by T0mek** [diasjorge/redmine-cli#7]
First I would like to thank you for this software - I found them very useful.

I found a couple issues and would be very graceful if you could help me with solving them.
1. How to do display version on the issue list? I mean the content of the fixed_version_id.
2. The redmine list command displays only issues that have NULL value in the fixed_version_id column, for other issues it just prints empty lines.
3. How to address custom fields? I would like to display them on list, edit them, or provide for the command "redmine new"
4. I there any debuig or trace , that I could turn on, and try to investigate those issues by myself?

Thanks in advance
Tomek

**Comment by swimfrog** [comment]
Hi T0mek,

> 1. How to do display version on the issue list? I mean the content of the fixed_version_id.

I thought that this would work by just specifying the field name in the configuration file, but after some testing, this turned out not to be the case. I pushed an update for this, and will push a new gem version soon (look for v0.1.7).

Once you're using the new version, you can specify "version" in the list of fields you give to "redmine install", or you can edit ~/.redmine and add " - version" to the "list_fields:" section in the order you require.

> 2. The redmine list command displays only issues that have NULL value in the fixed_version_id column, for other issues it just prints empty lines.

I think that this was a bug. I recently ran into it myself and fixed it so that other fields would be printed when version is NULL. Please get gem version 0.1.6 and see if it fixes your problem.

3. How to address custom fields? I would like to display them on list, edit them, or provide for the command "redmine new"

The good news is that you can include any custom field in the "list_fields:" section of your configuration file, and it should display the information in your list. "redmine install" doesn't offer it as a possible field in its prompt, because it doesn't know about the custom fields in your Redmine installation at that time. But you can specify those fields when you run the installer, if you like.

The bad news is that "redmine new" and "redmine update" only currently work with built-in fields, so they don't have any provision for modifying custom field data. I'll think about how this could be implemented, and I may add a feature to allow those fields to be edited.

4. I there any debuig or trace , that I could turn on, and try to investigate those issues by myself?

Unfortunately, the options for printing verbose/debug information are limited, currently. I generally enable ruby-debug to figure out problems, but this is not very user-friendly. I'll keep it in mind for a future version.

**Comment by T0mek** [comment]
Many thanks for your response and for updating repository.

Now versions are handled much better.
Empty lines are still displayed for issues not matching provided version, but I saw your comment about hack.
BTW. what is a problem with filtering versions in the same way as for example assignee? Is this some Redmine restriction?

As for custom fields, I was able to display them on the list, but I would need a possibility of providing custom field when creating or updating issue. It is because we have some of custom fields marked as required even for new issues.

It was my first step in Ruby programming, but I made successful prototype of creating new issue with custom field, below are code changes, you may find them useful.

<pre>
***************
*** 184,200 ****
        method_option :project,     :aliases => "-p", :desc => "project for the ticket"
        desc "new SUBJECT [DESCRIPTION]", "Create a new ticket"
        def new(subject, description="")
          params =
            Thor::CoreExt::HashWithIndifferentAccess.new(:subject => subject,
                                                         :description => description,
!                                                        :project => Redmine::Cli::config.default_project_id)
          params.merge!(options)
  
          unless params.project
            raise "No default project specified"
          end
  
          issue = Issue.create(ticket_attributes(params))
  
          say "Created ticket: #{link_to_issue(issue.id)}", :green
        rescue ActiveResource::ResourceNotFound
--- 185,210 ----
        method_option :project,     :aliases => "-p", :desc => "project for the ticket"
        desc "new SUBJECT [DESCRIPTION]", "Create a new ticket"
        def new(subject, description="")
+ 	custom_data = Array.new
+         custom_data[0] =  {  "value" =>  "CM" ,"id" => "2" } 
+         custom_data[1] =  { "value" =>  ["8"] , "id" => "6" }  
          params =
            Thor::CoreExt::HashWithIndifferentAccess.new(:subject => subject,
                                                         :description => description,
!                                                        :project => Redmine::Cli::config.default_project_id,
! 							:custom_fields => custom_data
! 							)
          params.merge!(options)
  
          unless params.project
            raise "No default project specified"
          end
  
+ @myvar=params
+ puts "NEW ISSUE #{@myvar}" 
          issue = Issue.create(ticket_attributes(params))
+ @myvar=issue.attributes
+ puts "ISSUE CREATED #{@myvar}" 
  
          say "Created ticket: #{link_to_issue(issue.id)}", :green
        rescue ActiveResource::ResourceNotFound
***************
*** 355,360 ****
--- 365,371 ----
            attributes[:priority_id]    = map_priority(options["priority"])if options["priority"].present?
            attributes[:tracker_id]     = map_tracker(options["tracker"])  if options["tracker"].present?
            attributes[:notes]          = options["notes"]                 if options["notes"].present?
+           attributes[:custom_fields]          = options["custom_fields"]                 if options["custom_fields"].present?
  
            attributes
          end	  
</pre>
Currently custom values are hard-coded, but they will be eventually passed by user.
I will try to do the same for updating issue. 

I also found another issue that is worth to be fixed,
The line        
<pre>issue = Issue.create(ticket_attributes(params))</pre>
returns no error even when issue is not created because of missing values in required fields.
I have checked that Redmine sends information about what is wrong:

<textarea>
 <?xml version=\"1.0\" encoding=\"UTF-8\"?><errors type=\"array\"><error>Found by can't be blank</error><error>Contact person can't be blank</error></errors>
</textarea>

 Maybe there is an easy way to utilize this information.

Regards,
Tomek
